### ISSUE TITLE
Finding solutions where big turns are cheeper than 2 small

### ISSUE THREAD

**Issue by denizsincar29** [kyo-takano/alphacube#7]
Hello! I found a rubik's cube robot that solves it very fast! However I need to find solutions that make it even faster, because a 180 degrees turn is actually 1.5 times longer than 90 degrees turn, not 2 times. So the algorythm needs to make a solution that does minimal cost solutions.
Is it achievable with alphacube?
Thank you!

**Comment by denizsincar29** [comment]
I mean it needs to use more 180 degrees turns if it will optimize the solving length

**Comment by kyo-takano** [comment]
Please at least skim through README before creating an issue.
